name: Deploy to Railway Dev Environment

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install packages
        run: npm install

      - name: Set up environment
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DEV_DB_PORT }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DEV_DB_HOST }}" >> $GITHUB_ENV

      - name: Migrate Database
        run: npm run migrate

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}
